<?php

namespace ProyB\DomainModelBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function buildQueryAllUsers()
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();
        $qb ->select('u')
            ->from('ProyBDomainModelBundle:User', 'u')
            ->orderBy('u.username', 'ASC');
        return $qb;
    }
}
